// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    History: typeof import('./src/components/History.vue')['default']
    LogList: typeof import('./src/components/LogList.vue')['default']
  }
}

export { }
